### ISSUE TITLE
no latest tag on Dockerhub

### ISSUE THREAD

**Issue by Shotgunosine** [kaczmarj/neurodocker#108]
None of the images on dockerhub are tagged latest, so the commands in the readme starting: `docker run --rm kaczmarj/neurodocker` fail, at least on Docker 17.09.0-ce-mac32 (19506).

**Comment by kaczmarj** [comment]
@Shotgunosine - I will update the commands in the readme to use a specific tag. Thank you.

**Comment by yarikoptic** [comment]
I am curious though why not to have some :latest?

**Comment by kaczmarj** [comment]
this was a conscious decision on our part to require users to use a versioned docker image. part of this is that neurodocker changes a lot. perhaps when the project has matured, we can use a `:latest` tag.
