### ISSUE TITLE
AFNI image doesn't include python

### ISSUE THREAD

**Issue by Shotgunosine** [kaczmarj/neurodocker#109]
I ran this command:
`docker run --rm kaczmarj/neurodocker:master generate -b ubuntu:17.04 -p apt --afni version=latest | docker build -t afni_nd -`

started the container:
`docker run -it afni_nd /bin/bash`

then tried to run:
`afni_system_check.py --check_all`

and received the error message: 
`/usr/bin/env: ‘python’: No such file or directory`

**Comment by kaczmarj** [comment]
@Shotgunosine - python isn't included in the default afni installation. Do you think it should be?

For now, can you use this command? It will add a python 2.7 conda environment.

```
docker run --rm kaczmarj/neurodocker:master generate -b ubuntu:17.04 -p apt --afni version=latest --miniconda env_name=afni27 conda_install="python=2.7" add_to_path=true
```
