### ISSUE TITLE
Readme example fails

### ISSUE THREAD

**Issue by arokem** [kaczmarj/neurodocker#118]
The example under "Generate Dockerfile (full)" fails with: 

`neurodocker: error: unrecognized arguments: --dcm2niix version=latest`

**Comment by kaczmarj** [comment]
thanks @arokem - i've been bitten by my own versioned docker image. `dcm2niix` is available in `kaczmarj/neurodocker:master`, not in `kaczmarj/neurodocker:v0.3.1`. I will update the readme soon.

i'm in the middle of a refactor to yaml, which I hope to merge by the end of the week. i will release a new version after that.

**Comment by kaczmarj** [comment]
hi @arokem - this has been fixed. i'll close this issue now.
