### ISSUE TITLE
problem with the full docker image (readme)

### ISSUE THREAD

**Issue by djarecka** [kaczmarj/neurodocker#119]
Trying to run examples from readme, I created the full Dockerfile with [this command] (https://github.com/kaczmarj/neurodocker#generate-dockerfile-full), but when I try to create a container I'm getting this:

```
/neurodocker/startup.sh: line 12: myfile.sh: No such file or directory
/neurodocker/startup.sh: line 13: arg1: command not found
``

**Comment by kaczmarj** [comment]
thanks @djarecka - this should be fixed. i also pruned the neurodocker example to only include the main software that neurodocker supports.

i'll close this now, but please reopen if you run into issues.
