### ISSUE TITLE
Example uses base debian stretch but neurodebian jessie

### ISSUE THREAD

**Issue by mvdoc** [kaczmarj/neurodocker#122]
This can cause problems: I tried to install mrtrix, but it would fail because couldn't find the correct dependencies. I'm happy to send a PR, but just wanted to make sure that it wasn't intended for some other reason.

**Comment by kaczmarj** [comment]
Hi @mvdoc - thanks for the bug report. feel free to submit a pr. can you elaborate on your issue? which command(s) failed?

**Comment by mvdoc** [comment]
So, there are two separate issues—one is that mrtrix is not available in NeuroDebian stretch, but @yarikoptic is helping out on that. The other is that the example uses different versions of neurodebian repository with the docker image, and it would be better to have the same versions.

When I'm trying to install mrtrix, this is what I get (I suspect this is because mrtrix is not yet available for stretch). I'm testing with jessie, and sending a PR soon.

```
+ apt-get update -qq
+ apt-get install -yq --no-install-recommends dcm2niix git-annex-standalone mrtrix
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mrtrix : Depends: libatkmm-1.6-1 (>= 2.22.1) but it is not installable
          Depends: libcairomm-1.0-1 (>= 1.6.4) but it is not installable
          Depends: libglibmm-2.4-1c2a (>= 2.44.0) but it is not installable
          Depends: libgsl0ldbl (>= 1.9) but it is not installable
          Depends: libgtkmm-2.4-1c2a (>= 1:2.24.0) but it is not installable
          Depends: libpangomm-1.4-1 (>= 2.36.0) but it is not installable
          Depends: libsigc++-2.0-0c2a (>= 2.2.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by mvdoc** [comment]
Wooops...you were faster than I was ;) I switched to jessie and not stretch because mrtrix is not available on stretch (yet).

And yep, mrtrix3 works perfectly, but I wanted to install the old version (mrtrix) to use some available workflows in nipype that are based on mrtrix (0.2) and not on mrtrix3,

**Comment by kaczmarj** [comment]
sorry to jump the gun @mvdoc. i would prefer to use debian stretch in the readme example. take a  look at #121. @djarecka is adding examples there. perhaps you could add an example of installing mrtrix on neurodebian jessie there. how does that sound to you?

you can also build mrtrix from source with `--mrtrix use_binaries=false git_hash=<hash>`, where `<hash>` is the git hash that you want to build from (on https://github.com/MRtrix3/mrtrix3)

**Comment by mvdoc** [comment]
No problem! Thanks :)
