### ISSUE TITLE
REQUEST: optional flag for curl retries

### ISSUE THREAD

**Issue by mgxd** [kaczmarj/neurodocker#128]
I'd love to have
* standardized `curl` (or `wget`, etc) command across supported software
* `--curl_args` or something similar that allows universally setting flags, such as `--retry` across the build

However, I'd be happy with just hardcoding `--retry 5` into missing lines, especially: https://github.com/kaczmarj/neurodocker/blob/c713d17ae0bae70aad7d8a03195ba73458b4e0d8/neurodocker/interfaces/freesurfer.py#L177

**Comment by kaczmarj** [comment]
`curl` should retry 5 times now. i'll keep this in mind for the refactor, and i'll keep it open until it's implemented.

**Comment by kaczmarj** [comment]
#151 will retry 5 times by default but will also allow the user to specify their own curl options. i'll let you know when it's in the `dev` branch

**Comment by kaczmarj** [comment]
release 0.4.0rc1 retries curl downloads 5 times by default. you can change that on the command line with the `curl_opts` option:

```shell
neurodocker generate docker -b debian:stretch -p apt \
    --ants version=2.2.0 curl_opts='-fsSL --retry 10'
```
