### ISSUE TITLE
Zenodo DOI

### ISSUE THREAD

**Issue by arokem** [kaczmarj/neurodocker#130]
Could you please create a Zenodo DOI? I would like to be able to cite neurodocker.

**Comment by kaczmarj** [comment]
sure @arokem . thanks for asking for this. i'll create a new release today or tomorrow, and zenodo should have it.

**Comment by kaczmarj** [comment]
Here it is! https://zenodo.org/record/1058998

**Comment by kaczmarj** [comment]
i had to remove the github release and re-release... i did the first release on github and the tag was not annotated, which caused an issue with neurodocker's version info.
