### ISSUE TITLE
 Unable to locate package libmng1 in ubuntu

### ISSUE THREAD

**Issue by djarecka** [kaczmarj/neurodocker#136]
` Unable to locate package libmng1` error when trying to install fsl using ubuntu 17.04 as a base image

**Comment by athanell** [comment]
@djarecka ,
Remove the libmng1 from your dockerfile and try to install fsl without it. Most likely only fslview is going to be affected.

**Comment by kaczmarj** [comment]
@djarecka - this should be fixed now. I removed `libmng1` from the FSL dependencies.
