### ISSUE TITLE
Add ability to install hcpre

### ISSUE THREAD

**Issue by tjhendrickson** [kaczmarj/neurodocker#138]
Hello,

I am very interested in neurodocker, however, I have interest in utilzing nipype in order to run my data through the human connectome project minimal preprocessing pipeline. Another developer generated a package named hcpre to piggyback off of nipype's existing infrastructure. 

-Tim

**Comment by kaczmarj** [comment]
Hi @tjhendrickson,

It should be possible to install `hcpre`. Can you try the following neurodocker command?

```shell
docker run --rm kaczmarj/neurodocker:v0.3.2 generate -b debian:stretch-slim -p apt --miniconda env_name="neuro" activate=true conda_install="python=2.7 numpy scipy traits" pip_install="hcpre nipype" | docker build -t hcpre -
```

This command builds an image based on Debian Stretch and includes a `conda` environment with Python 2.7, hcpe, nipype, and their dependencies. The output of that command is piped to `docker build ...` to build the Docker image.

You can run the image like this:
```shell
docker run --rm hcpre hcpipe.py --help
```

Please let me know if you have any questions about this.

**Comment by kaczmarj** [comment]
@tjhendrickson - i will close this issue for now. please reopen if necessary
