### ISSUE TITLE
Request: Declare miniconda pre-installed

### ISSUE THREAD

**Issue by effigies** [kaczmarj/neurodocker#147]
If I want to make use neurodocker to create two images, one built on top of the other (as in nipype), and both should install `conda` packages, then each Dockerfile created will attempt to install miniconda. It would be nice to have an argument (e.g. `preinstalled=True`) to pass to the second image to prevent neurodocker from doubling up.

**Comment by kaczmarj** [comment]
Hi @effigies - this is a great idea. I'll add it to #143.

**Comment by kaczmarj** [comment]
Addressed by #151 with the `preinstalled` option.

use will look something like `--miniconda env_name=neuro preinstalled=true conda_install="python=3.6 numpy"`. that will create a neuro environment with python3.5 and numpy and will not attempt to reinstall miniconda.

does that syntax look good to you?

**Comment by effigies** [comment]
Yup, looks great. And if I've already created the environment `neuro`, will this skip the `conda create` step, too?

**Comment by kaczmarj** [comment]
good point, i hadn't thought about that. that might require another flag. ideally there would be an option to `conda create` that would install into the environment if it exists or create the environment if it does not exist (sort of like the behavior of `mkdir -p`). but that doesn't seem to be the case.

what are you thoughts on the flag `env_exists=true`?

**Comment by effigies** [comment]
As a thought, you could have explicit options `create_env` and `use_env`, where `env_name` currently has `create_env` behavior on the first call and `use_env` on later. And perhaps `use_env` would imply `preinstalled=true`, for brevity.

On the other hand `preinstalled=true env_exists=true` has the advantage of being really explicit, so if that `create`/`use` doesn't seem instantly clear, maybe let's just go with that.

**Comment by kaczmarj** [comment]
@effigies - I'll go with `create_env` / `use_env`. the docs can explain the differences
