### ISSUE TITLE
fsl feat depends on `file`

### ISSUE THREAD

**Issue by ingo-m** [kaczmarj/neurodocker#149]
Hi! Thanks for creating neurodocker, very useful.

I noticed that with a default installation of fsl, I wasn't able to run fsl feat in my docker image. I figured out that there was a missing dependency, the 'file' bash command. It's easy to fix (i.e. `apt-get install file`), but it took me some time to figure out where the problem was coming from - maybe it would be worth installing 'file' by default (when installing fsl).

(Actually fsl feat probably only depends on `file` when using 'custom EV' files, but this is perhaps the most common use case.)

**Comment by kaczmarj** [comment]
Hi, thanks for the bug report. ‘file’ is a small binary so installing it with FSL by default is not a problem. Please let me know whether you would like to submit a pull request.

Jakub

**Comment by ingo-m** [comment]
Yes I can do that. 

Were would be the best location to include `file`? As far as I see, fsl dependencies are dealt with in `_install_binaries_deps()` in `neurodocker/neurodocker/interfaces/fsl.py`, right? But would that also have an effect if the user chooses to install fsl through neurodebian (like `--neurodebian pkgs="fsl-complete"`)?

**Comment by kaczmarj** [comment]
@ingo-m - these are the relevant lines: https://github.com/kaczmarj/neurodocker/blob/7441d77cfb5617b2e08824e4d8f9b44783074a52/neurodocker/interfaces/fsl.py#L132-L138

You can add `file` to both the `apt` and `yum` dict entries.

These changes will not affect installation of fsl through neurodebian. It's possible, however, that neurodebian includes`file` as a dependency.

**Comment by kaczmarj** [comment]
Closed by #150
