### ISSUE TITLE
Support for [E/M]EG software?

### ISSUE THREAD

**Issue by jona-sassenhagen** [kaczmarj/neurodocker#162]
I don't know if other dockers are already doing this, but maybe it would be interesting to add e.g. MNE-Python as an option?

MNE is currently not Python 3 compatible though, some of the 3D viz doesn't work in Py3k due to dependencies (mayavi etc).

There's also some special dependencies to Freesurfer that might be annoying to implement. But it's not that much.

**Comment by kaczmarj** [comment]
@jona-sassenhagen - i've used mne-python before, and as far as i know, it can be installed with pip or conda. can you elaborate on the freesurfer dependencies?

## conda install

```
docker run --rm kaczmarj/neurodocker:master generate docker \
    -b debian:stretch -p apt \
    --miniconda env_name=neuro \
                conda_install='python=2.7 mne' \
                activate=true
```

## pip install

```
docker run --rm kaczmarj/neurodocker:master generate docker \
    -b debian:stretch -p apt \
    --miniconda env_name=neuro \
                conda_install='python=2.7 scipy matplotlib scikit-learn mayavi jupyter' \
                pip_install='PySurfer mne' \
                activate=true
```

**Comment by jona-sassenhagen** [comment]
We recommend either:

`pip install -U mne`

for stable or pulling master from git for the most recent version, e.g.

`pip install https://github.com/mne-tools/mne-python/archive/master.zip`

Freesurfer is required for many of the source-level (MEG) preprocessing functions, i.e. constructing forward models. pysurfer is used for 3D viz of (volume) source space data, and for now depends on mayavi, unless you want to try some cutting-edge options. 

However, we have a .yaml file for dependencies now:
https://github.com/mne-tools/mne-python/blob/master/environment.yml
With that one (only on the most recent version), everything should work in python 3 I think.

@larsoner @choldgraf @jasmainak @agramfort

**Comment by larsoner** [comment]
Yes MNE is fully Python3 compatible now, including 3D viz, with that environment

**Comment by mvdoc** [comment]
An issue that came up for me about 5 months ago when creating a singularity container with MNE-Python was the need of installing MNE-C. IIRC some of the functionalities I wanted to use in Python were wrappers for MNE-C commands. To download MNE-C one needs to register and provide username/password, which makes it a bit annoying to code it. But it can be solved with

```bash
curl --data "account=<EMAIL>&password=<PASSWORD>&sendfile=9" \
http://www.nmr.mgh.harvard.edu/martinos/userInfo/data/MNE_register/login.php | tar xzv -C /opt/mne --strip 1
```

Maybe now MNE-Python doesn't rely on MNE-C anymore (after all I was using MNE-Python 0.13), but I just wanted to share this issue in case it can be useful for an MNE container.

**Comment by kaczmarj** [comment]
here is the command to create a container with mne, installed using mne's `environment.yml`:

```
$ docker run --rm kaczmarj/neurodocker:master generate docker \
    --base=debian:stretch \
    --pkg-manager=apt \
    --install gcc libc-dev libglu1-mesa libgl1-mesa-glx libxt6 \
    --user=mne \
    --copy environment.yml /home/mne/environment.yml \
    --miniconda create_env=mne yaml_file=/home/mne/environment.yml > Dockerfile
$ docker build -t mne .
```

for a bare installation of mne (akin to `pip install -U mne`):

```shell
$ docker run --rm kaczmarj/neurodocker:master generate docker \
    --base=debian:stretch \
    --pkg-manager=apt \
    --user=mne \
    --miniconda create_env=mne pip_install=mne > Dockerfile
$ docker build -t mne .
```

and to install mne's current master with pip:

```shell
$ docker run --rm kaczmarj/neurodocker:master generate docker \
    --base=debian:stretch \
    --pkg-manager=apt \
    --user=mne \
    --miniconda create_env=mne \
                pip_install=https://github.com/mne-tools/mne-python/tarball/master > Dockerfile
$ docker build -t mne .
```

i will close this issue for now because it is possible to install mne-python with neurodocker. please reopen if you have any issues or questions.

**Comment by jona-sassenhagen** [comment]
Cool!
