### ISSUE TITLE
HCP workbench support?

### ISSUE THREAD

**Issue by xaviergp** [kaczmarj/neurodocker#165]
Thank you for this fantastic work.
Is there a plan to add HCP workbench to this tool (HCP workbench command)?

**Comment by kaczmarj** [comment]
hi @xaviergp - you can install HCP workbench from neurodebian (a repository of neuroscience). to do that with neurodocker, use this command:

```
docker run --rm kaczmarj/neurodocker:0.4.0rc1 generate docker \
    --base neurodebian:stretch \
    --pkg-manager apt \
    --install connectome-workbench
```

please let me know if you have any questions.

**Comment by kaczmarj** [comment]
@xaviergp - i will close this for now as HCP workbench can be installed, but please reopen if you'd like to discuss more.
