### ISSUE TITLE
neurodocker generates files with unprintable characters [when used with docker]

### ISSUE THREAD

**Issue by satra** [kaczmarj/neurodocker#180]
@kaczmarj - we need to ensure that none of the generators contain non-printable characters.

```
+ '[' -n $'docker\r' -a -z '' ']'
+ '[' -x $'/usr/local/libexec/singularity/bootstrap-scripts/deffile-driver-docker\r.sh' ']'
```
on a unix system `cat -v filename` will show you the unprintable pieces. one can use dos2unix to remove them. otherwise, they go along even with copy and paste!

**Comment by kaczmarj** [comment]
@satra - i'm really sorry about all of the headaches that this bug caused. i can't see the unprintable characters on my debian machine with `cat -v`. the neurodocker command i tried is

```
neurodocker generate singularity \
  --base neurodebian:stretch \
  --pkg-manager apt \
  --install git emacs vim nano gedit
```

**Comment by satra** [comment]
@kaczmarj - try this:

```
docker run -it --rm kaczmarj/neurodocker:master generate singularity   --base neurodebian:stretch-non-free   --pkg-manager apt   --install eatmydata fsl-5.0-core fsl-mni152-templates   --run "eatmydata apt-get -y install --no-install-recommends file"   --add-to-entrypoint "source /etc/fsl/5.0/fsl.sh"
```

**Comment by kaczmarj** [comment]
@satra - yes, i can reproduce it now. thanks. building a new neurodocker image to see if that fixes the issue

**Comment by kaczmarj** [comment]
interestingly, running the neurodocker docker image produces the non-printable characters, but running a `pip`-installed neurdocker does not produce those characters

**Comment by satra** [comment]
@kaczmarj - perhaps we can update the readme. no fix is needed.

**Comment by yarikoptic** [comment]
FWIW. oh, just ran into it myself, I should remember to not use `-t` with a docker run of neurodocker!!!
