### ISSUE TITLE
Neurodocker how to start

### ISSUE THREAD

**Issue by relyativist** [kaczmarj/neurodocker#189]
Hello im new to docker^ could you please give step-by-step tutorial: btw when I try to start neurodocker I get the terminal:
![screenshot from 2018-07-05 12-00-40](https://user-images.githubusercontent.com/16246413/42313420-641779f0-804b-11e8-8a43-3c598d7d563b.png)
Could you please comment what I m doing wrong?

**Comment by yarkinvyacheslav** [comment]
Thanks for your reply. Is it possible to dockerize matlab script throught neurodocker?

**Comment by kaczmarj** [comment]
@yarkinvyacheslav - I don't have much experience with dockerizing matlab, but from what i know, it can be tricky. neurodocker supports installing matlab compiler runtime (MCR), but i'm not sure that that can run your script. of course, you can try it out.

you could also install matlab separately, but i don't know how you would activate it in the docker image.

neurodocker can install spm12 as well, if your script uses spm12.

**Comment by yarkinvyacheslav** [comment]
@kaczmarj I see, thank you.
Could you please clarify of using Matlab Runtime compiler under neurodocker. From the point if I have matlab script file how could I compile a prj with MCR. to run uit from terminal?

**Comment by kaczmarj** [comment]
@yarkinvyacheslav - i don't know how to use the matlab compiler runtime, but i do know how to install it. you can do so with the following neurodocker command:

```
$ docker run --rm kaczmarj/neurodocker:0.4.0 \
    generate docker --base=neurodebian:stretch-non-free --pkg-manager=apt \
    --matlabmcr version=2018a
```

**Comment by kaczmarj** [comment]
@relyativist - i will close this issue as resources exist to help users get started with neurodocker. i would be happy to hear suggestions for improving the documentation / examples if you are still having trouble. and please feel free to reopen the issue or open another one.
