### ISSUE TITLE
Run dcm2nii/dcm2niix

### ISSUE THREAD

**Issue by yarkinvyacheslav** [kaczmarj/neurodocker#190]
Hello, how could i run dcm2nii with neurodocker?

**Comment by kaczmarj** [comment]
@yarkinvyacheslav - you have two options:

1) build `dcm2niix` from source in a container:

```
docker run --rm kaczmarj/neurodocker:0.4.0 \
    generate docker \
    --base=debian:stretch-slim --pkg-manager=apt \
    --dcm2niix version=latest method=source
```

2) install `dcm2niix` through neurodebian:

```
docker run --rm kaczmarj/neurodocker:0.4.0 \
    generate docker \
    --base=neurodebian:stretch-non-free --pkg-manager=apt \
    --install dcm2niix
```

then build a docker image with the dockerfile, and run as you would normally run a docker image.

**Comment by kaczmarj** [comment]
i'll close this. please reopen or open a new issue if you want to discuss more.
