### ISSUE TITLE
exclude_paths for FSL?

### ISSUE THREAD

**Issue by xaviergp** [kaczmarj/neurodocker#209]
Hi!
Is it possible to use the exclude_paths option for FSL, or is this only for freesurfer?
Thanks!

**Comment by xaviergp** [comment]
Removing some FSL directories before running docker build removes those fsl folders from the final docker image, but the docker image size does not change. On the other hand, exclude_paths for freesurfer does decrease the docker image size. Would it be possible to add the exclude_paths option for FSL?

**Comment by kaczmarj** [comment]
sure, i will try to do this soon.

regarding the image size not decreasing after removing some fsl folders: docker images are made of layers, and editing a docker image modified the top layer. but the (removed) fsl folders still exist in the lower layers, so they count towards the total image size.

**Comment by xaviergp** [comment]
thank you very much, I will try this tonight!
