### ISSUE TITLE
generate directly from specs.json

### ISSUE THREAD

**Issue by satra** [kaczmarj/neurodocker#211]
it would be nice to have the following form:

```
neurodocker generate docker specs.json
```

also specs.json should optionally contain a version and neurodocker would say whether or not it supports that version of the spec.

**Comment by djarecka** [comment]
somehow related:
I can't find the specification or examples of json files that can be passed to neurodocker to `generate --file specs.json`.

**Comment by kaczmarj** [comment]
@satra @djarecka - this should be fixed now, although the spec version checking is not implemented yet.

I have added a `--json` flag, which will print the JSON representation of a particular neurodocker generate command. That can be saved to file and used with `neurodocker generate [docker|singularity] file.json`

**Comment by satra** [comment]
@kaczmarj - thank you!
