### ISSUE TITLE
could there be 0.4.3 release which would include the nd_freeze feature?

### ISSUE THREAD

**Issue by yarikoptic** [kaczmarj/neurodocker#243]

**Comment by kaczmarj** [comment]
@yarikoptic - absolutely, it's about time to release now!

**Comment by kaczmarj** [comment]
[https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5c2e5804f9189904b7b7e1bb](https://status.docker.com/pages/incident/533c6539221ae15e3f000031/5c2e5804f9189904b7b7e1bb) at the moment. i will release 0.4.3 once that's back up (i run tests in the python docker container).

**Comment by kaczmarj** [comment]
Ok, released 0.4.3!

**Comment by yarikoptic** [comment]
Awesome, thanks!

**Comment by yarikoptic** [comment]
BTW, unrelated... Data was mentioning possible renaming of the project - was the verdict made?

**Comment by kaczmarj** [comment]
as far as i know, no verdict was reached. but the reasoning for a potential name change was that neurodocker now supports singularity, and we'd like to be more general then neuroimaging.

**Comment by yarikoptic** [comment]
yeah -- the "neuro" is my main concern ;-)  so what were ideas/choices? IIRC Satra had some reasonable one. should we start a possible hunt in another issue or continue here?  I will start (vote on the ones you like or dislike ;))

**Comment by yarikoptic** [comment]
contrainer

**Comment by kaczmarj** [comment]
contrainer is interesting. i don't remember the name satra came up with. let's start a new issue.

**Comment by yarikoptic** [comment]
ok, start a new one... I found contrainer used already, but it wasn't updated in 3 years

**Comment by yarikoptic** [comment]
hey -- I think I got a good one!!! not even used!!!  start an issue before I forget!!! ;-)
