### ISSUE TITLE
GOTCH YA SNEAKY Neurodocker wiping out my /tmp!!!

### ISSUE THREAD

**Issue by yarikoptic** [kaczmarj/neurodocker#246]
It happened to me that from time to time I would be loosing connection to my ssh-agent and encounter some other oddities.  Due to overparallelization of activities never kinda really caught the offender... but NOW I GOTCH YA!!!

The problem is: singularity by default (at least in 2.6.1-dist I have) bind mounts host's /tmp inside the container. So if someone (as silly as yours truly) just uses conventional `singularity build` locally on Neurodocker produced Singularity file - he shoots himself into the foot potentially with lots of drama.

Is there an option (do not see in `singularity build --help`) or env var to disable bind mounting for build??? (besides changing system wide singularity configuration?).  Otherwise I am not sure... may be Neurodocker should add a bit of analysis into %post which would verify first that /tmp is clean to start with, and only then would remove /tmp/* (the same /var/tmp/*) in cleanup stage.  IMHO that would be reasonable/the best.  If someone builds with /tmp bound mount -- there is no reason to clean it since it would not be a part of the image anyways (let's forget about possible side-effects etc).  May be there is a way to disable /tmp bind mounting within Singularity ??

**Comment by kaczmarj** [comment]
I didn't think you'd figure me out :)

Just kidding. There is an environment variable you can set to change the temporary directory: `SINGULARITY_TMPDIR` ([docs](http://singularity.lbl.gov/build-environment#temporary-folders)). Unfortunately, it seems like at times in its history, singularity would not give proper respect to this variable.

With 3.x, there is a an option `singularity build --tmpdir PATH ...` which will set the temporary directory.

Can you try one of those things out?

If it works, perhaps instead of changing the `%post` instructions, the `neurodocker generate singularity --help` can include a note about `SINGULARITY_TMPDIR`.

**Comment by yarikoptic** [comment]
FWIW -- remembering to set per-app settings is unreliable for yours truly, who keeps forgetting about them. Yesterday, in one of those forgotten calls, the recipe produced by `docker run -it --rm kaczmarj/neurodocker:master generate singularity --base ubuntu:precise -p apt --install python-mvpa2` managed to wipe out not only `/tmp` but also `/dev/*` somehow - not sure I will try it again.  But it also was some not the most recent  `kaczmarj/neurodocker:master` as I have now discovered.
IIRC 3.x stopped carrying (or at least I see no `SINGULARITY_TMPDIR` explicitly in source code) about that variable.  But now I would need to remember to use not only envvar but also a cmdline option.

I wondered if there could be a better remedy, e.g. setting TMPDIR envvar to some temporary directory safe to wipe out may be (instead of hardcoded `/tmp`)?

**Comment by yarikoptic** [comment]
grr.... something is going on. while composing a reply was building another one, providing `--tmpdir /tmp/tmp` (may be singularity bug? I have ```3.0.3+ds```).  Ended up with both `/dev`,  and `/tmp` (has only sbuild left) wiped out again!  While I was not looking at it, terminal got filled with
```
...
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.rodata': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.init.text': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.note.gnu.build-id': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.text': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.data': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.altinstr_replacement': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.smp_locks': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/__bug_table': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.rodata.str1.1': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.parainstructions': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.text.unlikely': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/__ksymtab_strings': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/__ksymtab_gpl': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.altinstr_aux': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/__bpf_raw_tp_map': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.rodata.str1.8': Operation not permitted
rm: cannot remove '/tmp/tmp/sbuild-051580488/fs/sys/module/drm/sections/.ref.data': Operation not permitted
FATAL:   post proc: exit status 1
FATAL:   While performing build: while running engine: exit status 255
sudo singularity build --tmpdir /tmp/tmp fslanal.img Singularity  14.83s user 17.66s system 71% cpu 45.136 total
```

**Comment by kaczmarj** [comment]
@yarikoptic - i think i ran into the same issue before. it caused my laptop to do wonky things (like the screen to shut off). i posted an issue in https://github.com/sylabs/singularity/issues/2538 but apparently the build behavior is expected.

i think i will have to remove the calls to `rm -rf /tmp/*` in the generated Singularity (and Docker) recipes.

**Comment by yarikoptic** [comment]
<details>
<summary>and `/var/tmp` -- apparently that one is also bind mounted!</summary>

```
$> cat Singularity-tmp                          
Bootstrap: docker     
From: neurodebian:stretch

%post
export ND_ENTRYPOINT="/neurodocker/startup.sh"
mount | grep /tmp
for d in /var/lib/apt/lists/ /tmp/ /var/tmp/; do /bin/ls $d | head; done

$> sudo singularity build --tmpdir /tmp/tmp tmp Singularity-tmp
WARNING: Authentication token file not found : Only pulls of public images will succeed
Build target already exists. Do you want to overwrite? [N/y] y
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:22dbe790f71562dfd3d49406b1dfd1e85e50f3dd7cb2e97b3918376ca39cae4e
Skipping fetch of repeat blob sha256:dc23ef0c24aba8fa12efa247ef1de9df57872af0bfbe22722a338ee4102528d5
Skipping fetch of repeat blob sha256:d3225e459eb540cffb72cb0a11cc5dddda32bbdd92409342e4ac1a678b2090b9
Skipping fetch of repeat blob sha256:645fd6d0886f4db7abfbb7d4a80a24b0c78f3167b86c165949e8adbbbccf7582
Skipping fetch of repeat blob sha256:c480e1a7b244850a047f6eee13038f8d67737f8279019b74f472e08d3f927328
Copying config sha256:38bb3af2ed9f250de8803cb79d5d2c4408b8f87acaf4c4bc450499b12f1ac146
 2.25 KiB / 2.25 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Running post scriptlet
+ export ND_ENTRYPOINT=/neurodocker/startup.sh
+ mount
+ grep /tmp
/dev/sda1 on /tmp type ext4 (rw,relatime,discard,errors=remount-ro,stripe=32719)
proc on /tmp/tmp/sbuild-687271448/fs/proc type proc (rw,nosuid,nodev,noexec,relatime)
systemd-1 on /tmp/tmp/sbuild-687271448/fs/proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=47,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15514)
binfmt_misc on /tmp/tmp/sbuild-687271448/fs/proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
nfsd on /tmp/tmp/sbuild-687271448/fs/proc/fs/nfsd type nfsd (rw,relatime)
sysfs on /tmp/tmp/sbuild-687271448/fs/sys type sysfs (rw,nosuid,relatime)
udev on /tmp/tmp/sbuild-687271448/fs/dev type devtmpfs (rw,nosuid,relatime,size=8136432k,nr_inodes=2034108,mode=755)
devpts on /tmp/tmp/sbuild-687271448/fs/dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /tmp/tmp/sbuild-687271448/fs/dev/shm type tmpfs (rw,nosuid,nodev)
mqueue on /tmp/tmp/sbuild-687271448/fs/dev/mqueue type mqueue (rw,relatime)
hugetlbfs on /tmp/tmp/sbuild-687271448/fs/dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
/dev/sda1 on /var/tmp type ext4 (rw,relatime,discard,errors=remount-ro,stripe=32719)
/dev/sda1 on /tmp/tmp/sbuild-687271448/fs/var/tmp type ext4 (rw,relatime,discard,errors=remount-ro,stripe=32719)
tmpfs on /tmp/tmp/sbuild-687271448/fs/etc/resolv.conf type tmpfs (rw,nosuid,noexec,relatime,size=1632192k,mode=755)
/dev/sda1 on /tmp/tmp/sbuild-687271448/fs/etc/hosts type ext4 (rw,relatime,discard,errors=remount-ro,stripe=32719)
+ /bin/ls /var/lib/apt/lists/
+ head
+ /bin/ls /tmp/
+ head
qipc_sharedmemory_homeyohconfigcopyqcopyqs6e7a6afcaec5852962919360cc42a7df68d282d3
qipc_systemsem_copyqmutexd9f2f9cc1c362842383040e77b0d6667ed51e66c
qipc_systemsem_homeyohconfigcopyqcopyqs6e7a6afcaec5852962919360cc42a7df68d282d3
skypeforlinux Crashes
ssh-aDkyxWbEqAAz
systemd-private-2cc3aa95027f4032881afd0560b4fcef-apache2.service-A96Ywa
systemd-private-2cc3aa95027f4032881afd0560b4fcef-colord.service-FQybcf
systemd-private-2cc3aa95027f4032881afd0560b4fcef-rtkit-daemon.service-qpAyJ3
systemd-private-2cc3aa95027f4032881afd0560b4fcef-systemd-timesyncd.service-ATRcz1
systemd-private-2cc3aa95027f4032881afd0560b4fcef-upower.service-EBZt4r
+ /bin/ls /var/tmp/
+ head
aif_active_plugins
systemd-private-2cc3aa95027f4032881afd0560b4fcef-apache2.service-0QUHOc
systemd-private-2cc3aa95027f4032881afd0560b4fcef-colord.service-qdSFzh
systemd-private-2cc3aa95027f4032881afd0560b4fcef-rtkit-daemon.service-Ep6XZ4
systemd-private-2cc3aa95027f4032881afd0560b4fcef-systemd-timesyncd.service-LYO9s2
systemd-private-2cc3aa95027f4032881afd0560b4fcef-upower.service-ElkKjw
INFO:    Creating SIF file...
```
</details>

I think you should just set TMPDIR and rm that one at the end
```shell
$> ( TMPDIR="$(mktemp -d)"; echo dothings while TMPDIR=$TMPDIR; mktemp; ls -l ${TMPDIR}; rm -rf "${TMPDIR}"; ) 
dothings while TMPDIR=/home/yoh/.tmp/tmp.aWav6tAHay
/home/yoh/.tmp/tmp.aWav6tAHay/tmp.xNHJhHSo3j
total 0
-rw------- 1 yoh yoh 0 Mar 20 15:30 tmp.xNHJhHSo3j
```
so at least all kosher tools which do not hardcode `/tmp` anywhere would use that one instead.

**Comment by yarikoptic** [comment]
FWIW For now I am just sanitizing produced output by piping through `| sed -e 's, \(/var\)\?/tmp/\*,,g'`

**Comment by kaczmarj** [comment]
@yarikoptic - i merged the pr. i'll close this issue for now, but please reopen or create a new issues if the problem persists.

**Comment by yarikoptic** [comment]
Thank you!
