### ISSUE TITLE
R

### ISSUE THREAD

**Issue by sento4000** [kaczmarj/neurodocker#248]
Hi, when installing afni with R and r-pcks there is an error related to R installation:

vicente@vicente-GE63-7RD:~$ sudo docker run --rm kaczmarj/neurodocker:0.4.2 generate singularity --base=centos:7 --pkg-manager=yum  --afni version=latest method=source instal_r_pkgs=TRUE install_python3=TRUE > my_singularity
vicente@vicente-GE63-7RD:~$ sudo singularity build my_singularity.simg my_singularity 
Using container recipe deffile: my_singularity
Sanitizing environment
Adding base Singularity environment to container
tar: ./.exec: implausibly old time stamp -9223372036854775808
tar: ./.run: implausibly old time stamp -9223372036854775808
tar: ./.shell: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/exec: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/run: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/shell: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/start: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/test: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/01-base.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/90-environment.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/95-apps.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/99-base.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/libs: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/runscript: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/startscript: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d: implausibly old time stamp -9223372036854775808
tar: ./.test: implausibly old time stamp -9223372036854775808
tar: ./dev: implausibly old time stamp -9223372036854775808
tar: ./environment: implausibly old time stamp -9223372036854775808
tar: ./etc/hosts: implausibly old time stamp -9223372036854775808
tar: ./etc/resolv.conf: implausibly old time stamp -9223372036854775808
tar: ./etc: implausibly old time stamp -9223372036854775808
tar: ./home: implausibly old time stamp -9223372036854775808
tar: ./proc: implausibly old time stamp -9223372036854775808
tar: ./root: implausibly old time stamp -9223372036854775808
tar: ./singularity: implausibly old time stamp -9223372036854775808
tar: ./sys: implausibly old time stamp -9223372036854775808
tar: ./tmp: implausibly old time stamp -9223372036854775808
tar: ./var/tmp: implausibly old time stamp -9223372036854775808
tar: ./var: implausibly old time stamp -9223372036854775808
tar: .: implausibly old time stamp -9223372036854775808
Docker image path: index.docker.io/library/centos:7
Cache folder set to /root/.singularity/docker
Exploding layer: sha256:a02a4930cb5d36f3290eb84f4bfa30668ef2e9fe3a1fb73ec015fc58b9958b17.tar.gz
Exploding layer: sha256:8b5ee68a19e53a331d3b3068b3cb610048a7adf7e1f25db016a75d768afedcff.tar.gz
User defined %runscript found! Taking priority.
Adding environment to container
Running post scriptlet
+ export ND_ENTRYPOINT=/neurodocker/startup.sh
+ ND_ENTRYPOINT=/neurodocker/startup.sh
+ yum install -y -q bzip2 ca-certificates curl localedef unzip
Package ca-certificates-2018.2.22-70.0.el7_5.noarch already installed and latest version
Package curl-7.29.0-51.el7.x86_64 already installed and latest version
warning: /var/cache/yum/x86_64/7/base/packages/bzip2-1.0.6-13.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID f4a80eb5: NOKEY
Public key for bzip2-1.0.6-13.el7.x86_64.rpm is not installed
Importing GPG key 0xF4A80EB5:
 Userid     : "CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>"
 Fingerprint: 6341 ab27 53d7 8a78 a7c2 7bb1 24c6 a8a7 f4a8 0eb5
 Package    : centos-release-7-6.1810.2.el7.centos.x86_64 (@CentOS)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
+ yum clean packages
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras updates
0 package files removed
+ rm -rf /var/cache/yum/x86_64 /tmp/qt-trayicon-wc2565.png /tmp/toinstall.deb '/var/tmp/*'
+ localedef -i en_US -f UTF-8 en_US.UTF-8
+ chmod 777 /opt
+ chmod a+s /opt
+ mkdir -p /neurodocker
+ '[' '!' -f /neurodocker/startup.sh ']'
+ echo '#!/usr/bin/env bash'
+ echo 'set -e'
+ echo 'if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi'
+ chmod -R 777 /neurodocker
+ chmod a+s /neurodocker
+ yum install -y -q R R-devel compat-gcc-34 expat-devel gcc gcc-c++ gcc-gfortran git glib2-devel gsl-devel libXext-devel libXi-devel libXmu-devel libXpm-devel libXt-devel m4 make mesa-libGL-devel mesa-libGLU-devel netpbm-devel openmotif-devel python3 tcsh zlib-devel
install-info: No such file or directory for /usr/share/info/gettext.info.gz
install-info: No such file or directory for /usr/share/info/autoconf.info
install-info: No such file or directory for /usr/share/info/automake.info.gz
+ yum clean packages
Loaded plugins: fastestmirror, ovl
Cleaning repos: base extras updates
0 package files removed
+ rm -rf /var/cache/yum/x86_64 /tmp/qt-trayicon-au2565.png '/var/tmp/*'
+ curl -sSL --retry 5 -o /tmp/toinstall.deb http://mirrors.kernel.org/debian/pool/main/libx/libxp/libxp6_1.0.2-2_amd64.deb
+ dpkg -i /tmp/toinstall.deb
/bin/sh: line 48: dpkg: command not found
ABORT: Aborting with RETVAL=255
Cleaning up...

**Comment by sento4000** [comment]
Also failing in debian, ubuntu and neurodebian, i put the neurodebian example:

vicente@vicente-GE63-7RD:~$ sudo docker run --rm kaczmarj/neurodocker:0.4.2 generate singularity --base=neurodebian:stretch --pkg-manager=apt \
>  --afni version=latest method=source instal_r_pkgs=TRUE install_python3=TRUE --freesurfer version=6.0.0-min method=binaries --fsl version=5.0.10 method=binaries \
>  >my_singularity
vicente@vicente-GE63-7RD:~$ sudo singularity build my_singularity.simg my_singularity 
Using container recipe deffile: my_singularity
Sanitizing environment
Adding base Singularity environment to container
tar: ./.exec: implausibly old time stamp -9223372036854775808
tar: ./.run: implausibly old time stamp -9223372036854775808
tar: ./.shell: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/exec: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/run: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/shell: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/start: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions/test: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/actions: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/01-base.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/90-environment.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/95-apps.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env/99-base.sh: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/env: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/libs: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/runscript: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d/startscript: implausibly old time stamp -9223372036854775808
tar: ./.singularity.d: implausibly old time stamp -9223372036854775808
tar: ./.test: implausibly old time stamp -9223372036854775808
tar: ./dev: implausibly old time stamp -9223372036854775808
tar: ./environment: implausibly old time stamp -9223372036854775808
tar: ./etc/hosts: implausibly old time stamp -9223372036854775808
tar: ./etc/resolv.conf: implausibly old time stamp -9223372036854775808
tar: ./etc: implausibly old time stamp -9223372036854775808
tar: ./home: implausibly old time stamp -9223372036854775808
tar: ./proc: implausibly old time stamp -9223372036854775808
tar: ./root: implausibly old time stamp -9223372036854775808
tar: ./singularity: implausibly old time stamp -9223372036854775808
tar: ./sys: implausibly old time stamp -9223372036854775808
tar: ./tmp: implausibly old time stamp -9223372036854775808
tar: ./var/tmp: implausibly old time stamp -9223372036854775808
tar: ./var: implausibly old time stamp -9223372036854775808
tar: .: implausibly old time stamp -9223372036854775808
Docker image path: index.docker.io/library/neurodebian:stretch
Cache folder set to /root/.singularity/docker
[5/5] |===================================| 100.0% 
Exploding layer: sha256:bc9ab73e5b14b9fbd3687a4d8c1f1360533d6ee9ffc3f5ecc6630794b40257b7.tar.gz
Exploding layer: sha256:b323f9a9fdf6eb0b3b4a40e3e969f18def6c12bd5ec49949a0d33cc6e48d811b.tar.gz
Exploding layer: sha256:9294e84bac26e93e46e519dec54fb88e8ef10d1845aba4c8b62d8d1f78290df9.tar.gz
Exploding layer: sha256:474b78678a62f392d7a8c718849bf769ea1738889df46de3275f933617d32808.tar.gz
Exploding layer: sha256:e955ce81ae0db65ddb0957ffbb6273b241213feaf83b85598fe85c97fb618ca7.tar.gz
Exploding layer: sha256:e441ed5dd1c0da8419a8806620561e4874afc56cc83d45f9b5ec10be1a6782ac.tar.gz
User defined %runscript found! Taking priority.
Adding environment to container
Running post scriptlet
+ export ND_ENTRYPOINT=/neurodocker/startup.sh
+ apt-get update -qq
+ apt-get install -y -q --no-install-recommends apt-utils bzip2 ca-certificates curl locales unzip
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libapt-inst2.0 libc-l10n libcurl3 libgssapi-krb5-2 libidn2-0 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libnghttp2-14 libpsl5 librtmp1 libssh2-1 libssl1.0.2 libssl1.1 libunistring0 openssl
Suggested packages:
  bzip2-doc krb5-doc krb5-user zip
Recommended packages:
  krb5-locales publicsuffix
The following NEW packages will be installed:
  apt-utils bzip2 ca-certificates curl libapt-inst2.0 libc-l10n libcurl3 libgssapi-krb5-2 libidn2-0 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libnghttp2-14 libpsl5 librtmp1 libssh2-1
  libssl1.0.2 libssl1.1 libunistring0 locales openssl unzip
0 upgraded, 23 newly installed, 0 to remove and 11 not upgraded.
Need to get 10.3 MB of archives.
After this operation, 30.2 MB of additional disk space will be used.
Get:1 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 libssl1.0.2 amd64 1.0.2q-1~deb9u1 [1300 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libapt-inst2.0 amd64 1.4.8 [192 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 apt-utils amd64 1.4.8 [410 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 bzip2 amd64 1.0.6-8.1 [47.5 kB]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libc-l10n all 2.24-11+deb9u3 [820 kB]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libkeyutils1 amd64 1.5.9-9 [12.4 kB]
Get:9 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libkrb5support0 amd64 1.15-1+deb9u1 [61.9 kB]
Get:10 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libk5crypto3 amd64 1.15-1+deb9u1 [119 kB]
Get:11 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libkrb5-3 amd64 1.15-1+deb9u1 [311 kB]
Get:12 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libgssapi-krb5-2 amd64 1.15-1+deb9u1 [155 kB]
Get:13 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 locales all 2.24-11+deb9u3 [3287 kB]
Get:2 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 libssl1.1 amd64 1.1.0j-1~deb9u1 [1354 kB]
Get:14 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 ca-certificates all 20161130+nmu1+deb9u1 [182 kB]
Get:15 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libunistring0 amd64 0.9.6+really0.9.3-0.1 [279 kB]
Get:16 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libidn2-0 amd64 0.16-1+deb9u1 [60.7 kB]
Get:17 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libnghttp2-14 amd64 1.18.1-1 [79.1 kB]
Get:18 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libpsl5 amd64 0.17.0-3 [41.8 kB]
Get:19 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 librtmp1 amd64 2.4+20151223.gitfa8646d.1-1+b1 [60.4 kB]
Get:20 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libssh2-1 amd64 1.7.0-1 [138 kB]
Get:21 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libcurl3 amd64 7.52.1-5+deb9u8 [292 kB]
Get:22 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 curl amd64 7.52.1-5+deb9u8 [228 kB]
Get:23 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 unzip amd64 6.0-21 [170 kB]
Get:3 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 openssl amd64 1.1.0j-1~deb9u1 [746 kB]
Fetched 10.3 MB in 2s (5053 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libapt-inst2.0:amd64.
(Reading database ... 6778 files and directories currently installed.)
Preparing to unpack .../00-libapt-inst2.0_1.4.8_amd64.deb ...
Unpacking libapt-inst2.0:amd64 (1.4.8) ...
Selecting previously unselected package apt-utils.
Preparing to unpack .../01-apt-utils_1.4.8_amd64.deb ...
Unpacking apt-utils (1.4.8) ...
Selecting previously unselected package libssl1.0.2:amd64.
Preparing to unpack .../02-libssl1.0.2_1.0.2q-1~deb9u1_amd64.deb ...
Unpacking libssl1.0.2:amd64 (1.0.2q-1~deb9u1) ...
Selecting previously unselected package libssl1.1:amd64.
Preparing to unpack .../03-libssl1.1_1.1.0j-1~deb9u1_amd64.deb ...
Unpacking libssl1.1:amd64 (1.1.0j-1~deb9u1) ...
Selecting previously unselected package bzip2.
Preparing to unpack .../04-bzip2_1.0.6-8.1_amd64.deb ...
Unpacking bzip2 (1.0.6-8.1) ...
Selecting previously unselected package libc-l10n.
Preparing to unpack .../05-libc-l10n_2.24-11+deb9u3_all.deb ...
Unpacking libc-l10n (2.24-11+deb9u3) ...
Selecting previously unselected package libkeyutils1:amd64.
Preparing to unpack .../06-libkeyutils1_1.5.9-9_amd64.deb ...
Unpacking libkeyutils1:amd64 (1.5.9-9) ...
Selecting previously unselected package libkrb5support0:amd64.
Preparing to unpack .../07-libkrb5support0_1.15-1+deb9u1_amd64.deb ...
Unpacking libkrb5support0:amd64 (1.15-1+deb9u1) ...
Selecting previously unselected package libk5crypto3:amd64.
Preparing to unpack .../08-libk5crypto3_1.15-1+deb9u1_amd64.deb ...
Unpacking libk5crypto3:amd64 (1.15-1+deb9u1) ...
Selecting previously unselected package libkrb5-3:amd64.
Preparing to unpack .../09-libkrb5-3_1.15-1+deb9u1_amd64.deb ...
Unpacking libkrb5-3:amd64 (1.15-1+deb9u1) ...
Selecting previously unselected package libgssapi-krb5-2:amd64.
Preparing to unpack .../10-libgssapi-krb5-2_1.15-1+deb9u1_amd64.deb ...
Unpacking libgssapi-krb5-2:amd64 (1.15-1+deb9u1) ...
Selecting previously unselected package locales.
Preparing to unpack .../11-locales_2.24-11+deb9u3_all.deb ...
Unpacking locales (2.24-11+deb9u3) ...
Selecting previously unselected package openssl.
Preparing to unpack .../12-openssl_1.1.0j-1~deb9u1_amd64.deb ...
Unpacking openssl (1.1.0j-1~deb9u1) ...
Selecting previously unselected package ca-certificates.
Preparing to unpack .../13-ca-certificates_20161130+nmu1+deb9u1_all.deb ...
Unpacking ca-certificates (20161130+nmu1+deb9u1) ...
Selecting previously unselected package libunistring0:amd64.
Preparing to unpack .../14-libunistring0_0.9.6+really0.9.3-0.1_amd64.deb ...
Unpacking libunistring0:amd64 (0.9.6+really0.9.3-0.1) ...
Selecting previously unselected package libidn2-0:amd64.
Preparing to unpack .../15-libidn2-0_0.16-1+deb9u1_amd64.deb ...
Unpacking libidn2-0:amd64 (0.16-1+deb9u1) ...
Selecting previously unselected package libnghttp2-14:amd64.
Preparing to unpack .../16-libnghttp2-14_1.18.1-1_amd64.deb ...
Unpacking libnghttp2-14:amd64 (1.18.1-1) ...
Selecting previously unselected package libpsl5:amd64.
Preparing to unpack .../17-libpsl5_0.17.0-3_amd64.deb ...
Unpacking libpsl5:amd64 (0.17.0-3) ...
Selecting previously unselected package librtmp1:amd64.
Preparing to unpack .../18-librtmp1_2.4+20151223.gitfa8646d.1-1+b1_amd64.deb ...
Unpacking librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1+b1) ...
Selecting previously unselected package libssh2-1:amd64.
Preparing to unpack .../19-libssh2-1_1.7.0-1_amd64.deb ...
Unpacking libssh2-1:amd64 (1.7.0-1) ...
Selecting previously unselected package libcurl3:amd64.
Preparing to unpack .../20-libcurl3_7.52.1-5+deb9u8_amd64.deb ...
Unpacking libcurl3:amd64 (7.52.1-5+deb9u8) ...
Selecting previously unselected package curl.
Preparing to unpack .../21-curl_7.52.1-5+deb9u8_amd64.deb ...
Unpacking curl (7.52.1-5+deb9u8) ...
Selecting previously unselected package unzip.
Preparing to unpack .../22-unzip_6.0-21_amd64.deb ...
Unpacking unzip (6.0-21) ...
Setting up libapt-inst2.0:amd64 (1.4.8) ...
Setting up libnghttp2-14:amd64 (1.18.1-1) ...
Setting up apt-utils (1.4.8) ...
Setting up unzip (6.0-21) ...
Setting up librtmp1:amd64 (2.4+20151223.gitfa8646d.1-1+b1) ...
Setting up bzip2 (1.0.6-8.1) ...
Setting up libssl1.0.2:amd64 (1.0.2q-1~deb9u1) ...
Setting up libssh2-1:amd64 (1.7.0-1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Setting up libunistring0:amd64 (0.9.6+really0.9.3-0.1) ...
Setting up libssl1.1:amd64 (1.1.0j-1~deb9u1) ...
Setting up libc-l10n (2.24-11+deb9u3) ...
Setting up openssl (1.1.0j-1~deb9u1) ...
Setting up libkeyutils1:amd64 (1.5.9-9) ...
Setting up ca-certificates (20161130+nmu1+deb9u1) ...
Updating certificates in /etc/ssl/certs...
151 added, 0 removed; done.
Setting up locales (2.24-11+deb9u3) ...
Generating locales (this might take a while)...
Generation complete.
Setting up libidn2-0:amd64 (0.16-1+deb9u1) ...
Setting up libpsl5:amd64 (0.17.0-3) ...
Setting up libkrb5support0:amd64 (1.15-1+deb9u1) ...
Setting up libk5crypto3:amd64 (1.15-1+deb9u1) ...
Setting up libkrb5-3:amd64 (1.15-1+deb9u1) ...
Setting up libgssapi-krb5-2:amd64 (1.15-1+deb9u1) ...
Setting up libcurl3:amd64 (7.52.1-5+deb9u8) ...
Setting up curl (7.52.1-5+deb9u8) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for ca-certificates (20161130+nmu1+deb9u1) ...
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
+ apt-get clean
+ rm -rf /var/lib/apt/lists/deb.debian.org_debian_dists_stretch-updates_InRelease /var/lib/apt/lists/deb.debian.org_debian_dists_stretch-updates_main_binary-amd64_Packages.lz4 /var/lib/apt/lists/deb.debian.org_debian_dists_stretch_Release /var/lib/apt/lists/deb.debian.org_debian_dists_stretch_Release.gpg /var/lib/apt/lists/deb.debian.org_debian_dists_stretch_main_binary-amd64_Packages.lz4 /var/lib/apt/lists/lock /var/lib/apt/lists/neuro.debian.net_debian_dists_data_InRelease /var/lib/apt/lists/neuro.debian.net_debian_dists_data_main_binary-amd64_Packages.lz4 /var/lib/apt/lists/neuro.debian.net_debian_dists_stretch_InRelease /var/lib/apt/lists/neuro.debian.net_debian_dists_stretch_main_binary-amd64_Packages.lz4 /var/lib/apt/lists/partial /var/lib/apt/lists/security.debian.org_debian-security_dists_stretch_updates_InRelease /var/lib/apt/lists/security.debian.org_debian-security_dists_stretch_updates_main_binary-amd64_Packages.lz4 /tmp/qt-trayicon-mZ2565.png /var/tmp/*
+ sed -i -e s/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/ /etc/locale.gen
+ dpkg-reconfigure --frontend=noninteractive locales
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
+ update-locale LANG=en_US.UTF-8
+ chmod 777 /opt
+ chmod a+s /opt
+ mkdir -p /neurodocker
+ [ ! -f /neurodocker/startup.sh ]
+ echo #!/usr/bin/env bash
+ echo set -e
+ echo if [ -n "$1" ]; then "$@"; else /usr/bin/env bash; fi
+ chmod -R 777 /neurodocker
+ chmod a+s /neurodocker
+ apt-get update -qq
+ apt-get install -y -q --no-install-recommends curl ed g++ gcc git libglib2.0-dev libglu1-mesa-dev libgsl-dev libmotif-dev libnetpbm10-dev libxext-dev libxi-dev libxpm-dev libxt-dev m4 make nlibxmu-headers nmesa-common-dev python3 r-base r-base-dev tcsh zlib1g-dev
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nlibxmu-headers
E: Unable to locate package nmesa-common-dev
ABORT: Aborting with RETVAL=255
Cleaning up...

**Comment by sento4000** [comment]
Hi there, already solved the problem in the recipe, if you check lines 55 and 56 you will see that it says:

nlibxmu-headers
nmesa-common-dev
and it should be:
libxmu-headers
mesa-common-dev

I don't know how neurodocker generates this but could you fix it?

thanks for the help.

**Comment by kaczmarj** [comment]
@sento4000 - thanks for investigating. the lines are generated from the template at https://github.com/kaczmarj/neurodocker/blob/01cdd22e8f0a43a110492dd5928deb043640d555/neurodocker/templates/afni.yaml#L51. Would you like to change it and submit a PR?

**Comment by kaczmarj** [comment]
closed by #255
