### ISSUE TITLE
eddy

### ISSUE THREAD

**Issue by malywladek** [kaczmarj/neurodocker#254]

**Comment by kaczmarj** [comment]
hi @malywladek - i assume this issue was related to https://github.com/kaczmarj/neurodocker/issues/191#issuecomment-454762104.

i recommend installing fsl (including fsleyes and eddy) from neurodebian:

```bash
$ docker run --rm kaczmarj/neurodocker:0.4.3 generate docker \
  --base=neurodebian:stretch-non-free \
  --pkg-manager=apt \
  --install apt_opts='' fsl-5.0-complete fsl-5.0-eddy-nonfree fsleyes \
  --add-to-entrypoint 'source /etc/fsl/5.0/fsl.sh' > Dockerfile

$ docker build -t fsl .
```

**Comment by akemisetti** [comment]
Hi
I tried the above command and got the following error.

Gtk-Message: Failed to load module "canberra-gtk-module"
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
The program 'fsleyes' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
(Details: serial 960 error_code 2 request_code 155 minor_code 24)
(Note to programmers: normally, X errors are reported asynchronously;
that is, you will receive the error a while after causing it.
To debug your program, run it with the --sync command line
option to change this behavior. You can then get a meaningful
backtrace from your debugger if you break on the gdk_x_error() function.)

I am using docker on ubuntu 18.04 with Nvidia drivers

== /sys/devices/pci0000:00/0000:00:01.0/0000:01:00.0 ==
modalias : pci:v000010DEd00001F36sv00001028sd00000926bc03sc00i00
vendor : NVIDIA Corporation
driver : nvidia-driver-435 - distro non-free
driver : nvidia-driver-440 - distro non-free recommended
driver : xserver-xorg-video-nouveau - distro free builtin

am I missing anything else?

Thanks
Anil
