### ISSUE TITLE
'conda clean --source-cache' is deprecated

### ISSUE THREAD

**Issue by effigies** [kaczmarj/neurodocker#260]
```
WARNING: 'conda clean --source-cache' is deprecated.     Use 'conda build purge-all' to remove source cache files.
```

This runs after `conda clean -tipsy`. Looking at the docs, `-s` doesn't appear, so this should probably be `conda clean -tipy`.

**Comment by kaczmarj** [comment]
thanks @effigies. i guess it could be `conda clean -tipy` or `conda clean --all`. i'll fix this soon
