### ISSUE TITLE
git URL in environment.yml file

### ISSUE THREAD

**Issue by akeshavan** [kaczmarj/neurodocker#264]
if the environment.yml file has a package in a github repo, like https://github.com/nipy/dmriprep/blob/master/docker/environment.yml#L14 then it can't install because git has already been removed at an earlier stage i'm assuming

```
  Error [Errno 2] No such file or directory: 'git': 'git' while executing command git clone -q https://github.com/akeshavan/nipype /src/nipype
Cannot find command 'git' - do you have 'git' installed and in your PATH?
```

**Comment by kaczmarj** [comment]
@akeshavan - can you show me your dockerfile or neurodocker command? `git` shouldn't be removed anywhere.

by the way, for github urls, you can do `pip install https://github.com/USER/REPOSITORY/tarball/BRANCH`, which does not require git. i see you have an FSL URL too, which this won't work for.

**Comment by kaczmarj** [comment]
@akeshavan - are you still facing this issue?

**Comment by akeshavan** [comment]
To be honest I haven't looked at this for a while! Lets close for now!
