### ISSUE TITLE
Make it possible to use eatmydata for at least apt

### ISSUE THREAD

**Issue by yarikoptic** [kaczmarj/neurodocker#268]
There was an elderly https://github.com/kaczmarj/neurodocker/issues/60 which was closed without an explanation, so decided to open a brand new one
I guess could be an option specific to `apt` manager

**Comment by kaczmarj** [comment]
i'm hesitant to add this `eatmydata` adds something to the dockerfile that might cause issues, and i don't think that risk outweighs the speed improvements. `eatmydata` might not be installable on all the systems users want to use; it causes the behavior between `apt` and `yum` to be different when i would like it to be as similar as possible; and i'm not confident that it will work right every time (it seems a bit unsafe). this is why i closed that other issue — i should have explained back then.

i'm going to close this issue given the points i listed above.

**Comment by yarikoptic** [comment]
eatmydata causes no change to anyone's behavior besides avoiding constant 'sync' all the time - so I am not sure what changes you have in mind @kaczmarj .  Clearly you can't expect "apt" and "yum" to behave exactly the same way since they are doing different things to different packages ;-)
as for installability - AFAIK available on all debian system, hence my request was somewhat targetting.
But hey - you are the boss, it was just a suggestion. FWIW I have been using eatmydata without any side effects for long time ... FWIW all NeuroDebian docker containers now actually have
```shell
$> docker run -it --rm neurodebian:sid ls -l /usr/local/bin/apt-get
lrwxrwxrwx 1 root root 18 Mar 27 00:02 /usr/local/bin/apt-get -> /usr/bin/eatmydata
```
so I kinda solved this issue a bit more generally, at least for neurodebian docker based images ;-)
