### ISSUE TITLE
[FSL] Only install FLIRT from FSL

### ISSUE THREAD

**Issue by pykao** [kaczmarj/neurodocker#282]
Dear all,

If I want to just use the FLIRT from FSL. Is that a way to just install this function without installing the whole FSL libraries?

Best,
P Kao

**Comment by kaczmarj** [comment]
Hi @pykao,

At the moment, this isn't really possible. For now, you can install fsl from neurodebian, which will have a smaller footprint than installing the regular fsl binaries. You can take a look at the examples in this repository to see how to do that.

If you want a very small container only with flirt, you can minify it with reprozip. There is an example in the readme with that as well.

In the future, there are plans to have containers for individual tools like flirt. There is a related issue (https://github.com/nipy/nipype/issues/2367) but those containers don't exist yet.

**Comment by pykao** [comment]
Hi @kaczmarj,

Thank you for your reply. Neurodocker is a useful tool.

Best,
pykao
