### ISSUE TITLE
Minizing Docker Image - 2+ commands?

### ISSUE THREAD

**Issue by unimusic** [kaczmarj/neurodocker#283]
In the README example, minimizing the docker using reprozip only gives the example where one command is used, `cmd="antsMotionCorr -d 3 -a /home/func.nii.gz -o /home/func_avg.nii.gz"`.

The associated reprozip command is
`neurodocker reprozip trace ants-container "$cmd"`

What if I have 2 or more commands? How would I go about doing this?

Thanks!

- Angela

**Comment by kaczmarj** [comment]
hi @unimusic - you can pass multiple commands to the trace command. just be sure to wrap each command in quotes.

```
neurodocker reprozip trace ants-container "$cmd" "$cmd2" "$cmd3" "$cmdN"
```

**Comment by unimusic** [comment]
Okay great. Thank you!
