### ISSUE TITLE
miniconda installation permission error

### ISSUE THREAD

**Issue by jdkent** [kaczmarj/neurodocker#286]
It appears installing packages as non-root with miniconda causes some permission errors.

## Generate Dockerfile Command
```
docker run --rm kaczmarj/neurodocker:0.5.0 generate docker --base=neurodebian:stretch-non-free --pkg-manager=apt --user=neuro --miniconda conda_install="python=3.6" create_env="neuro_py36" activate=true > Dockerfile_bad
```

## Error from building
```
[Errno 13] Permission denied: '/.cph_tmpke0gsvu_'
[Errno 13] Permission denied: '/.cph_tmpnw7al20z'
```

## The fix
```
docker run --rm kaczmarj/neurodocker:0.5.0 generate docker --base=neurodebian:stretch-non-free --pkg-manager=apt --user=neuro --workdir="/home/neuro" --miniconda conda_install="python=3.6" create_env="neuro_py36" activate=true > Dockerfile_fix
```
So you have to be outside the root directory and in a folder you have permission to create and delete files from for this to work.

**Comment by kaczmarj** [comment]
thanks @jdkent -- though i'm not sure how this could be fixed in neurodocker. during dockerfile / singularity file generation, the current directory is not known, and permissions are definitely not known. perhaps this could be added to the "known issues" section of the readme.

**Comment by effigies** [comment]
Is this still an issue? I think it should have been fixed upstream, but that may not have hit recent conda. The fix is to set `--workdir` to something owned by the user if you're going to drop root permissions.

**Comment by jdkent** [comment]
I just tested the example again, this is fixed, thanks @effigies!
