### ISSUE TITLE
Getting a 404 on the default SPM download

### ISSUE THREAD

**Issue by arokem** [kaczmarj/neurodocker#288]
The link on this line:

https://github.com/kaczmarj/neurodocker/blob/37b62b5ae34f88b4da21fc62f44131b1f5c02ebb/neurodocker/templates/spm12.yaml#L9

no longer exists

**Comment by gllmflndn** [comment]
Hi @arokem 
As mentioned elsewhere the files in this directory can change at any time and should be used with care.
The new file is `spm12_latest_Linux_R2019a.zip`. I also notice that all the links could now use `https`.

**Comment by kaczmarj** [comment]
thanks @arokem and @gllmflndn -- i will update the links.
