### ISSUE TITLE
Is docker pull supported for images?

### ISSUE THREAD

**Issue by tashrifbillah** [kaczmarj/neurodocker#291]
Can I do:

`docker pull kaczmarj/neurodocker/ants:VERSION`

Asking this question, because BIDS supports [`docker pull bids/base_ants`](https://neurohackweek.github.io/docker-for-scientists/03-pulling_and_running/)

I see your [generate.sh](https://github.com/kaczmarj/neurodocker/blob/master/examples/fsl/generate.sh) script for fsl. But, I don't want to `--install` as you have there, rather pull an image and use as it is needed.

**Comment by kaczmarj** [comment]
hi @tashrifbillah - i have created docker images of several ants versions, available at https://hub.docker.com/r/kaczmarj/ants ([github repo](https://github.com/kaczmarj/ANTs-builds)). is it just ants you want to use this with?

i have created images for several (but not all) of the software packages that neurodocker supports. you can find them under my dockerhub account https://hub.docker.com/r/kaczmarj

**Comment by tashrifbillah** [comment]
Thanks @kaczmarj , I think I can advance with the two sources you gave.
Should I need more guidance, I shall reach out in future.
