### ISSUE TITLE
Problem building image from BIDS/example

### ISSUE THREAD

**Issue by mathdugre** [kaczmarj/neurodocker#295]
I am trying to minify the size of BIDS/example however I am running into some errors.

I used the [bids app example](https://github.com/BIDS-Apps/example) with the [corr/IPCAS_4 (BIDS)](http://datasets.datalad.org/?dir=/corr/RawDataBIDS/IPCAS_4) dataset.

### Normal MWE
```bash
# Generate image from bids/example
$ neurodocker generate docker -b bids/example -p apt > Dockerfile
$ docker build -t bids-example .

# Start a container
$ docker run --rm -itd -v $PWD/data:/data -v $PWD/outputs:/outputs --name bids-example --security-opt=seccomp:unconfined bids-example

# Execute command in the container
$ cmd1='python3 /run.py /data/IPCAS_4 /outputs participant --participant_label 0026190'
$ cmd2='python3 /run.py /data/IPCAS_4 /outputs group'
$ neurodocker reprozip trace bids-example "$cmd1" "$cmd2"

# Build image from reprozip file
reprounzip docker setup neurodocker-reprozip.rpz img
```

However when using reprounzip I have this error:
```bash
Step 6/6 : RUN     chmod +x /busybox /rpzsudo &&     cd / && (tar zpxf /reprozip_data.tgz -U --recursive-unlink --numeric-owner --strip=1 --null -T /rpz-files.list || /busybox echo "TAR reports errors, this might or might not prevent the execution to run")
 ---> Running in 0c770eeaff35
tar: etc: Cannot unlink: Device or resource busy
tar: etc/resolv.conf: Cannot unlink: Device or resource busy
tar: Exiting with failure status due to previous errors
TAR reports errors, this might or might not prevent the execution to run
```

I tried to launch the image interactively afterwards but the tool remove file to much (e.g. bahs was gone)

### ndminify MWE
I then tried a modified (and less aggressive version of the tool) #258.
 
When using this version starting from the previous `bids-example` container I get:
```bash
# Specify commands to run
$ cmd0='mkdir /test' # dummy folder to remove
$ cmd1='touch /test/file'
$ cmd2='python3 /run.py /data/IPCAS_4 /outputs participant --participant_label 0026190'
$ cmd3='python3 /run.py /data/IPCAS_4 /outputs group'

# Execute command with ndminify
ndminify -c bids-example -d /test --commands "$cmd0" "$cmd1" "$cmd2" "$cmd3"
```

When using this version of the tool, I get errors due to `bet` not being installed in the final image.

**Comment by kaczmarj** [comment]
@mathdugre i got a chance to look into this. i think the tar errors are benign -- they've come up on the reprozip github issues but don't seem to cause problems.

looks like the `$PATH` and `$LD_LIBRARY_PATH` variables are not correct in the 'reprozipped' image.

```shell
docker run --rm -it reprounzip_image_yzrjp25ry9:latest /busybox ash
/busybox --install
export PATH="/usr/lib/fsl/5.0:$PATH"
export LD_LIBRARY_PATH="/usr/lib/fsl/5.0:$LD_LIBRARY_PATH"
bet --help
```

i wrote the `ndminify` script to make it easier to have a usable container after minification. (when you minimize aggressively in the standard way, things we might take for granted like `bash` can be removed, and it often becomes very difficult to use a container interactively)

so here is what i did with `ndminify`. i would suggest using that to minify for now. i pushed some updates so please re-install with

```
pip install --no-cache-dir docker  https://github.com/kaczmarj/neurodocker/tarball/add/minify-gently
```

```
ndminify -c bids-example -d /usr/bin /usr/lib --commands "$cmd1" "$cmd2"

# This step does not preserve environment variables, so they have to be reset.
docker export bids-example | docker import - bids-example-minified

docker run --rm -it bids-example-minified bash
export PATH=/usr/lib/fsl/5.0:$PATH
export LD_LIBRARY_PATH=/usr/lib/fsl/5.0:$LD_LIBRARY_PATH
bet -h
```

you can write a Dockerfile to set these things up for you. the minification would be an intermediate process.

```Dockerfile
FROM bids-example-minified
ENV PATH=/usr/lib/fsl/5.0:$PATH \
        LD_LIBRARY_PATH=/usr/lib/fsl/5.0:$LD_LIBRARY_PATH
ENTRYPOINT ["python3", "/run.py"]
```

this minified image is 510 MB, whereas the original `bids/example` image is 1.13 GB.

**Comment by mathdugre** [comment]
Hi @kaczmarj, sorry for the long delay. Unfortunately, this doesn't seem to work. While the `bet -h` command executes correctly, commands that use the tool won't execute; e.g. `python3 /run.py /data /outputs participant`.

This is the error message:
```
bet /data/IPCAS_4/sub-0026190/ses-1/anat/sub-0026190_ses-1_run-1_T1w.nii.gz /outputs/sub-0026190_ses-1_run-1_brain.nii.gz
/usr/lib/fsl/5.0/bet: 1: /usr/lib/fsl/5.0/bet: /bin/remove_ext: not found
/usr/lib/fsl/5.0/bet: 1: /usr/lib/fsl/5.0/bet: /bin/remove_ext: not found
/usr/lib/fsl/5.0/bet: 1: /usr/lib/fsl/5.0/bet: /bin/imtest: not found
/usr/lib/fsl/5.0/bet: 154: [: =: unexpected operator
/usr/lib/fsl/5.0/bet: 236: /usr/lib/fsl/5.0/bet: /bin/bet2: not found
```

It looks like the symlinks are broken after using `docker export bids-example | docker import - bids-example-minified`. I am currently working on a bash script to fix this issue.

**Comment by mathdugre** [comment]
Hi @kaczmarj, I figured out my issue. When I copied the environment variable in the minified container I was not exporting them. Now everything works, thank you :)

**Comment by kaczmarj** [comment]
excellent! thanks for the followup, and sorry the container minification is tricky. it will get better over time... do you mind posting the commands you used for the minification? that will help future readers.

**Comment by mathdugre** [comment]
To obtain the minified container image I followed the below steps:
*Note that I used the [bids app example](https://github.com/BIDS-Apps/example) with the [corr/IPCAS_4 (BIDS)](http://datasets.datalad.org/?dir=/corr/RawDataBIDS/IPCAS_4) dataset.

```
# Install the updated version of ndminify
pip install --no-cache-dir docker  https://github.com/kaczmarj/neurodocker/tarball/add/minify-gently
```

```
# Initialize environment variable
export DOCKER_FLAG='-v /path/to/data:/data -v /path/to/outputs:/outputs'
export cmd1='python3 /run.py /data/IPCAS_4 /outputs participant'
export cmd2='python3 /run.py /data/IPCAS_4 /outputs group'
```

```
docker run  --rm -itd --entrypoint="bash" --name bids-example $DOCKER_FLAG bids/example
ndminify -c bids-example -d /usr/bin /usr/lib --commands "$cmd1" "$cmd2"

# This step does not preserve environment variables, so they have to be reset.
docker export bids-example | docker import - bids-example-minified
```

Create a Docker file as follow:
```
 FROM bids-example-minified

 ENV POSSUMDIR=/usr/share/fsl/5.0 \
     HOSTNAME=9af3e0876db7 \
     LD_LIBRARY_PATH=/usr/lib/fsl/5.0: \
     HOME=/root \
     FSLDIR=/usr/share/fsl/5.0 \
     FSLMULTIFILEQUIT=TRUE \
     FSLTCLSH=/usr/bin/tclsh \
     TERM=xterm \
     PATH=/usr/lib/fsl/5.0:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
     FSLOUTPUTTYPE=NIFTI_GZ \
     FSLWISH=/usr/bin/wish \
     PWD=/ \
     PYTHONPATH=         

ENTRYPOINT ["/run.py"] 
```

Execute the minimized container:
```
docker run --rm -it $DOCKER_FLAG bids-example-minified /data/IPCAS_4 /outputs participant
docker run --rm -it $DOCKER_FLAG bids-example-minified /data/IPCAS_4 /outputs group
```

**Comment by kaczmarj** [comment]
thank you @mathdugre - i will close this issue now. please re-open or open a new issue if you experience problems in the future or for any questions.
