### ISSUE TITLE
Miniconda throwing error during docker build

### ISSUE THREAD

**Issue by switt4** [kaczmarj/neurodocker#301]
Hi,

I am trying to build a docker container with miniconda.  I have followed the example and the Dockerfile is generated without any errors.

```
docker run --rm kaczmarj/neurodocker:0.6.0 generate docker --base neurodebian:stretch --pkg-manager apt --afni version=latest method=binaries --fsl version=6.0.0 methods=binaries --miniconda create_env=neuro conda_install='python=3.7 numpy pandas scipy' pip_install='nilearn matplotlib' > Dockerfile
```

However, when I go to build the container, I get the following error:

```
RemoveError: 'setuptools' is a dependency of conda and cannot be removed from
conda's operating environment.
```

A quick google search for this error message suggests that it might be caused by conda's install/update/remove functionality.  Any suggestions for how to solve this?

Thanks in advance,

suzanne

**Comment by kaczmarj** [comment]
hi @switt4 - i am not able to reproduce your issue. i used a slightly smaller version of the dockerfile (excluding afni and fsl), and the image built without error. here are the commands i used:

```
jakub@dash:~$ mkdir /tmp/test
jakub@dash:~$ cd /tmp/test/
jakub@dash:/tmp/test$ docker run --rm kaczmarj/neurodocker:0.6.0 generate docker --base neurodebian:stretch --pkg-manager apt --miniconda create_env=neuro conda_install='python=3.7 numpy pandas scipy' pip_install='nilearn matplotlib' > Dockerfile
jakub@dash:/tmp/test$ docker build -t test .
```

i have searched for the issue online, and others suggest installing `setuptools` via conda to solve the issue. as a side note, installing miniconda should install `setuptools` (that is a very important library for installing packages), but perhaps installing it explicitly adds it to some database that prevents conda from trying to remove it.
