### ISSUE TITLE
ANTs 2.2.0 version string

### ISSUE THREAD

**Issue by effigies** [kaczmarj/neurodocker#40]
The current ANTs version string is `2.1.0.post789-g0740f`. I did ensure that the ANTs version in `nipype` will accept that string as [equivalent to 2.2.0](https://github.com/nipy/nipype/blob/master/nipype/interfaces/ants/base.py#L58-L60), but it would probably be a good idea to fix this, if this framework permits patching.

**Comment by kaczmarj** [comment]
Thanks for this. What kind of patch did you have in mind? Should the [`neurodocker.interfaces.ANTs`](https://github.com/kaczmarj/neurodocker/blob/master/neurodocker/interfaces/ants.py#L23) class interpret `2.1.0.post789-g0740f` as `2.2.0`?

**Comment by effigies** [comment]
I meant it would be nice if the package itself was rebuilt with the correct version information. I'm not positive on everything that's needed to make it work, but see https://lists.alioth.debian.org/pipermail/neurodebian-users/2017-June/001155.html.

This could be out-of-scope for Neurodocker, though.

**Comment by kaczmarj** [comment]
Ah, I see. Thanks for the clarification. That's out-of-scope for Neurodocker, but it is relevant the project where I built the various ANTs releases ([kaczmarj/ANTs-builds](https://github.com/kaczmarj/ANTs-builds)).

I will rebuild version 2.2.0 and modify the minor version in [Version.cmake](https://github.com/stnava/ANTs/blob/master/Version.cmake#L12).

**Comment by kaczmarj** [comment]
Hi @effigies - I fixed the bug and re-compiled ANTs. You can find the binaries [here](https://www.dropbox.com/s/2f4sui1z6lcgyek/ANTs-Linux-centos5_x86_64-v2.2.0-0740f91.tar.gz?dl=0). I cloned ANTs, checked out to the commit for version 2.2.0 (0740f9111e5a9cd4768323dc5dfaa7c29481f9ef), fixed the version bugs as per the most recent [ANTs commit](https://github.com/stnava/ANTs/commit/e170c7c4695643c0f0e08e619778ef45b6b4632c), and compiled.

Here is the version output:

```shell
$> antsRegistration --version
ANTs Version: 2.2.0.dev815-g0740f
Compiled: Jun 27 2017 17:39:25
```

Does that look correct now?

kaczmarj/ANTs-builds#5

**Comment by effigies** [comment]
Hmm. It ideally shouldn't have the `dev` bit, since it is the actual release commit, but that probably can't be helped. Hopefully they handle the next release better and we don't need to worry about the N in `devN` to make version comparisons.

**Comment by kaczmarj** [comment]
@effigies - closing for now. reopen if necessary
