### ISSUE TITLE
Freesurfer pipeline fails inside neurodocker image because of missing perl 

### ISSUE THREAD

**Issue by schahid** [kaczmarj/neurodocker#71]
Hi,
I generated a docker image with this command:
neurodocker generate -b centos:7 -p yum --freesurfer version=6.0.0 > Dockerfile

another command to generate Dockerfile with miniconda (2 with python2.7) and pasted the docker commands again in the docker file generated with the first command. At the end, installed my freesurfer pipeline built with nipype.

The freesurfer command nu_correct failed because it could not find perl.
Therefore, I added perl in the yum commands to install perl. Then everything went fine.

The generated-full.Dockerfile in examples folder is also missing perl.

So I think perl should be installed as a dependency before installing freesurfer.

Thanks a lot,

**Comment by kaczmarj** [comment]
Hi @schahid - thanks for the report. I am able to reproduce the issue. Do you want to submit a PR so you can be attributed? I don't mind doing it. Here are [the relevant lines](https://github.com/kaczmarj/neurodocker/blob/master/neurodocker/interfaces/freesurfer.py#L114-L115).

**Comment by kaczmarj** [comment]
@schahid - it looks like the email address you used when you made that commit is not associated with your github account. you won't show up as a contributor until you associate the two. not essential, just fyi. thank you again for the pr.

<img width="304" alt="screen shot 2017-08-15 at 9 11 48 am" src="https://user-images.githubusercontent.com/17690870/29317428-edd3616a-8199-11e7-8188-fd40e56ea9cd.png">

**Comment by schahid** [comment]
Thanks a lot Jakub for your considerations.

Best regards,

--
Shahid.
