### ISSUE TITLE
neurodebian - ubuntu installation error

### ISSUE THREAD

**Issue by sulantha2006** [kaczmarj/neurodocker#78]
with ubuntu base installation of neurodebian fails with gpg keyserver error. 

`https://dl.dropbox.com/s/zxs209o955q6vkg/neurodebian.gpg
gpgkeys: protocol `https' not supported
gpg: no handler for keyserver scheme `https'
gpg: WARNING: unable to fetch URI https://dl.dropbox.com/s/zxs209o955q6vkg/neurodebian.gpg: keyserver error
Removing intermediate container 17b51386ea90
The command '/bin/sh -c apt-get update -qq && apt-get install -yq --no-install-recommends dirmngr gnupg && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && curl -sSL http://neuro.debian.net/lists/jessie.us-nh.full > /etc/apt/sources.list.d/neurodebian.sources.list && apt-key adv --fetch-keys https://dl.dropbox.com/s/zxs209o955q6vkg/neurodebian.gpg && (apt-key adv --refresh-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9 || true) && apt-get update' returned a non-zero code: 2
ERROR: Build failed: The command '/bin/sh -c apt-get update -qq && apt-get install -yq --no-install-recommends dirmngr gnupg && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && curl -sSL http://neuro.debian.net/lists/jessie.us-nh.full > /etc/apt/sources.list.d/neurodebian.sources.list && apt-key adv --fetch-keys https://dl.dropbox.com/s/zxs209o955q6vkg/neurodebian.gpg && (apt-key adv --refresh-keys --keyserver hkp://pool.sks-keyservers.net:80 0xA5D32F012649A5A9 || true) && apt-get update' returned a non-zero code: 2
ERROR: Build failed with exit code 2`

**Comment by kaczmarj** [comment]
Hi @sulantha2006 - can you share the command you used to generate the Dockerfile? Is this on Ubuntu 16.04 by any chance?

**Comment by sulantha2006** [comment]
`from neurodocker import Dockerfile

specs = {
    'pkg_manager': 'apt',
    'check_urls': False,
    'instructions': [
        ('base', 'debian:stretch'),
        ('install', ['git', 'vim']),
        ('afni', {'version': 'latest'}),
        ('ants', {'version': '2.2.0'}),
        ('freesurfer', {'version': '6.0.0', 'min': True}),
        ('fsl', {'version': '5.0.10', 'use_binaries': True}),
        ('user', 'neuro'),
        ('miniconda', {
            'env_name': 'default',
            'python_version': '3.6.1',
            'conda_install': 'numpy pandas traits',
            'pip_install': 'nipype'}),
        ('user', 'root'),
        ('mrtrix3', {'use_binaries': True}),
        ('neurodebian', {'os_codename': 'jessie', 'download_server': 'usa-nh',
                         'pkgs': ['git-annex-standalone', 'dcm2niix']}),
        ('spm', {'version': '12', 'matlab_version': 'R2017a'}),
        ('user', 'neuro'),
        ('env', {'KEY_A': 'VAL_A', 'KEY_B': 'VAL_B'}),
        ('env', {'KEY_C': 'based on $KEY_A'}),
    ]
}
# Create Dockerfile.
df = Dockerfile(specs)`

**Comment by kaczmarj** [comment]
@sulantha2006 - I can reproduce this error on ubuntu 16.04.  I modified the code to add the gpg key by piping it from `curl` to `apt-key`. This resolves the issue and allows us to use https. I updated the neurodebian test to use ubuntu 16.04.

You can also use a [neurodebian docker image](https://hub.docker.com/r/library/neurodebian/) as a base:

```
neurodocker generate --base neurodebian:xenial-non-free --pkg-manager apt \
--install ants dcm2niix \
--no-check-urls
```

As for the formatting, you can format your code by wrapping multiple lines in backticks (three on each side). See [these docs](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code) for more info.

\```python
import numpy
\```

**Comment by sulantha2006** [comment]
Thanks.
