### ISSUE TITLE
Can not build AFNI using Neurodocker

### ISSUE THREAD

**Issue by ross-mitchell** [kaczmarj/neurodocker#98]
Hi: 

I am getting the following error during the build of AFNI using a dockerfile generated by neurodocker:

> configure: Need to download and build NLopt
> trying URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
> Error in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  : 
>   cannot open URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
> Execution halted
> /bin/tar: This does not look like a tar archive
> 
> gzip: stdin: unexpected end of file
> /bin/tar: Child returned status 1
> /bin/tar: Error is not recoverable: exiting now
> Warning message:
> In untar(tarfile = "nlopt-2.4.2.tar.gz") :
>   '/bin/tar -xf 'nlopt-2.4.2.tar.gz'' returned error code 2
> configure: Starting to install library to /tmp/RtmpqWSb5X/R.INSTALL4236c845677/nloptr/nlopt-2.4.2
> ./configure: line 3325: cd: nlopt-2.4.2: No such file or directory

The docker file was generated using the following command:

> docker run --rm kaczmarj/neurodocker:master generate -b ubuntu -p apt --afni version=latest use_binaries=true > afni_docker

I get the same error if I do not include the 'use_binaries' flag.

The build is then initiated using:

> docker build -f afni_docker -t afni .

My docker version info:

> docker version
> Client:
>  Version:      17.06.2-ce
>  API version:  1.30
>  Go version:   go1.8.3
>  Git commit:   cec0b72
>  Built:        Tue Sep  5 20:12:06 2017
>  OS/Arch:      darwin/amd64
> 
> Server:
>  Version:      17.06.2-ce
>  API version:  1.30 (minimum version 1.12)
>  Go version:   go1.8.3
>  Git commit:   cec0b72
>  Built:        Tue Sep  5 19:59:19 2017
>  OS/Arch:      linux/amd64
>  Experimental: true

The build proceeds for quite a while, but appears to get stuck while installing R packages, at this line in the generated dockerfile:

> /opt/afni/rPkgsInstall -pkgs ALL 

The error is strange, because if you copy / paste the troublesome url into your browser:

> http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz

 the download starts and completes.

**Comment by kaczmarj** [comment]
Hi @ross-mitchell - thank you for the report. I was able to replicate your issue. The download error is a little misleading, but lines right above it are telling:

```
checking nlopt.h usability... no
checking nlopt.h presence... no
checking for nlopt.h... no
```

Turns out the system package `nlopt` can be installed with `apt-get`, and then the R package will install successfully: https://stackoverflow.com/a/38340228/5666087

For now, you can manually add `libnlopt-dev` to line 57 of your Dockerfile, before the trailing slash. I will put out a patch later today.

As an aside, it is good practice to use specific base images, like `ubuntu:16.04` as opposed to `ubuntu`, which is equivalent to `ubuntu:latest`. The `latest` tag corresponds to 16.04 in this case, but this mapping can change over time.

**Comment by kaczmarj** [comment]
@ross-mitchell - if this fix works for you, please feel free to submit a PR. [This line](https://github.com/kaczmarj/neurodocker/blob/b332a4f55f39973fff9458c7ed068bbf1400d25b/neurodocker/interfaces/afni.py#L124) would have to be modified to install `libnlopt-dev`. I am happy to do this, but it would be nice if you got the credit for discovering this bug.

**Comment by ross-mitchell** [comment]
Will do. thanks for you help. The PR will not happen until this evening, due to circumstances…  - Ross
--
J Ross Mitchell, PhD
Professor of Radiology, Mayo Clinic College of Medicine
Senior Associate Consultant, Department of Research
Precision Neurotherapeutics Innovations Lab
Mayo Clinic, 5777 East Mayo Blvd., Phoenix AZ 85054
SSB 2-700

**Comment by mattcieslak** [comment]
I know this is closed, but I'm running into this issue still using d02f8ed7940748348c1076da5163e217f3408d64 on master. It looks like this PR got refactored into this line https://github.com/kaczmarj/neurodocker/blob/d02f8ed7940748348c1076da5163e217f3408d64/neurodocker/interfaces/interfaces.py#L37? If so I'll make a new PR

**Comment by kaczmarj** [comment]
@mattcieslak - yes, i forgot to include `libnlopt-dev` during the refactor. please submit a PR adding 'libnlopt-dev' to the `apt` portion of the line you linked above. 

unfortunately i cannot see how to install `nlopt-devel` on distros that use `yum` (without having to use `epel`). for now, we can include `nlopt` installation for `apt` distros.
